version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3307:3306

  app:
    container_name: flask_app
    restart: always
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 5000:5000
    volumes:
      - ./:/code/

volumes:
  db_data:
